### ISSUE TITLE
[Feature request] HEX color support in messages

### ISSUE THREAD

**Issue by d3adwolf** [LeandroTheDev/feex_ranks_restored#2]
Very much missing support for color and HEX color in plugin posts, it would be very cool if you could do multiple colors at once in one post.

**Comment by d3adwolf** [comment]
That's the way it is at the moment:
<img width="277" alt="image" src="https://github.com/LeandroTheDev/feex_ranks_restored/assets/43119052/f6f63eae-f504-4521-9b13-e132f86caafb">

**Comment by d3adwolf** [comment]
And this is how I have it in my Minecraft server, but would like a similar thing in Unturned:
<img width="503" alt="image" src="https://github.com/LeandroTheDev/feex_ranks_restored/assets/43119052/223024b3-a721-41cd-be09-dcad6a74f9aa">

**Comment by d3adwolf** [comment]
@LeandroTheDev

**Comment by LeandroTheDev** [comment]
Done in [2d254eb](https://github.com/LeandroTheDev/feex_ranks_restored/commit/2d254eb048f705b485af555941224573569d71b3)
