### ISSUE TITLE
[Feature request] HEX (not RGB) color support in messages

### ISSUE THREAD

**Issue by d3adwolf** [LeandroTheDev/feex_ranks_restored#3]
Hi, thanks for the latest release, the bugs have really gone away. The current version of RGB support is applied to the whole line, which is not very good, I would like to color the text differently.

Plus because it's RGB color support is limited and I can't use many colors from color-hex.com they are just painted to the nearest similar one, for example, just white or gray, and it doesn't let me choose shades, even with specifying a specific RGB.

It would be really nice to see an implementation of HEX colors like in Config.json - that would be a must have solution.

An example of the colors I showed in https://github.com/LeandroTheDev/feex_ranks_restored/issues/2#issuecomment-2143776865.

**Comment by LeandroTheDev** [comment]
Do you have some plugin source that i can get any reference from?

i don't know any plugin that uses hex color for messages

**Comment by d3adwolf** [comment]
[AirdropManager3](https://github.com/RestoreMonarchyPlugins/AirdropManager3)

**Comment by LeandroTheDev** [comment]
Done in [5d56004](https://github.com/LeandroTheDev/feex_ranks_restored/commit/5d56004b91878cd21fe5c1a10accf41f1b9155cc)
